name: BuildAndDeploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish --configuration Release --no-build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CSharpRegexBenchmark
          path: /home/runner/work/CSharpRegexBenchmark/CSharpRegexBenchmark/CSharpRegexBenchmark/bin/Release/net7.0/publish/